#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

HISTFILE=~/.zhistfile
HISTSIZE=5000
SAVEHIST=150000
setopt appendhistory autocd extendedglob nomatch notify
unsetopt beep
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
#zstyle :compinstall filename '/home/ubuntu/.zshrc'

#autoload -Uz compinit
#compinit
# End of lines added by compinstall

if [[ -s source "${ZDOTDIR:-$HOME}/.aliases.sh" ]]; then
  source "${ZDOTDIR:-$HOME}/.aliases.sh"
fi

